/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf --transform
Author: Harley Torrisi (https://sketchfab.com/htorrisi)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-pirates-chest-084162b39dfd4808a6c481193463690d
Title: Low-Poly Pirates Chest
*/

import { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import { Group } from 'three';

export function Model(props: any) {
  const group = useRef<Group>();
  const { nodes, materials, animations } = useGLTF('/scene-transformed.glb') as any
  const { actions } = useAnimations(animations, group) as any
  const [isChestOpening, setIsChestOpening] = useState(false);

  useEffect(() => {
    group.current?.rotation.set(0, 0.05, 0);
    group.current?.scale.addScalar(0.5);

    onclick = () => {
      if (!isChestOpening) {
        actions?.OpenNormal?.play();
        actions.OpenNormal.setLoop(0, 0);
        actions.OpenNormal.clampWhenFinished = true;
        setIsChestOpening(true);
      }
    }   
  }, [actions])

  useFrame((state, delta) => {
    if (group.current) {
        if (isChestOpening && state.clock.elapsedTime < 1) {
          group.current.scale.addScalar(0.5 * delta);
        }
        if (state.clock.elapsedTime > 1 && state.clock.elapsedTime < 2) {
          group.current.scale.addScalar(delta * -0.7)
        }
        if (state.clock.elapsedTime > 2) {
          group.current.rotateY(0.05 * delta);
        }
    }
  })

  

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Mesh_ChestBase" position={[0, 0, -78]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Mesh_ChestLid" position={[0, 38.809, 134.528]}>
            <group name="Object_9" position={[0, -116.766, -2.175]}>
              <mesh name="Mesh_ChestLid_Material_#2_0" geometry={nodes['Mesh_ChestLid_Material_#2_0'].geometry} material={materials.Material_2} />
            </group>
          </group>
        </group>
        <mesh name="Mesh_ChestBase_Material_#2_0" geometry={nodes['Mesh_ChestBase_Material_#2_0'].geometry} material={materials.Material_2} position={[0, 132.5, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
